# Generated by Django 4.2.2 on 2023-06-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('check', 'Check'), ('cash', 'Cash'), ('cryptocurrency', 'Cryptocurrency'), ('debit_card', 'Debit Card'), ('mobile_payment', 'Mobile Payment'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('samsung_pay', 'Samsung Pay'), ('venmo', 'Venmo')], default='cash', max_length=30),
        ),
    ]
