# Generated by Django 4.2.2 on 2023-07-11 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_suppliermodel_customermodel_created_and_more'),
        ('billings', '0002_alter_transactionmodel_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customermodel'),
        ),
    ]
