# Generated by Django 4.2.2 on 2023-07-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0003_alter_transactionmodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='amount_currency',
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
