# Generated by Django 4.2.2 on 2023-07-11 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_remove_transactionmodel_amount_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='customer',
        ),
    ]
