# Generated by Django 4.2.2 on 2023-07-11 04:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordersmodel_place'),
        ('billings', '0005_remove_transactionmodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='order',
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordersmodel')),
            ],
            options={
                'db_table': 'pr_invoice_t',
            },
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billings.invoicemodel'),
            preserve_default=False,
        ),
    ]
