# Generated by Django 4.2.2 on 2023-07-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0006_remove_transactionmodel_order_invoicemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='is_individual',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='invoice_number',
            field=models.CharField(max_length=200),
        ),
    ]
