# Generated by Django 4.2.2 on 2023-07-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_ordersmodel_status'),
        ('billings', '0008_alter_invoicemodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemodel',
            name='order',
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='orders',
            field=models.ManyToManyField(to='orders.ordersmodel'),
        ),
    ]
