# Generated by Django 4.2.2 on 2023-07-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0009_remove_invoicemodel_order_invoicemodel_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='status',
            field=models.CharField(max_length=21),
        ),
    ]
