# Generated by Django 4.2.2 on 2023-07-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0010_alter_transactionmodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicemodel',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='transactionmodel',
            options={'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciónes'},
        ),
    ]
