# Generated by Django 4.2.2 on 2023-08-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0011_alter_invoicemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='apellido',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='nombre',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
