# Generated by Django 4.2.2 on 2023-08-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0012_invoicemodel_apellido_invoicemodel_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicemodel',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='transactionmodel',
            options={'verbose_name': 'Transation', 'verbose_name_plural': 'Transations'},
        ),
        migrations.RenameField(
            model_name='invoicemodel',
            old_name='apellido',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='invoicemodel',
            old_name='nombre',
            new_name='name',
        ),
    ]
