# Generated by Django 4.2.2 on 2023-06-17 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationmodel',
            old_name='Checkin',
            new_name='checkin',
        ),
    ]
