# Generated by Django 4.2.2 on 2023-06-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_checkin_reservationmodel_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemodel',
            name='name_type',
            field=models.CharField(choices=[('family', 'Family'), ('individual', 'Individual'), ('couples', 'Couples'), ('friends', 'Friends')], default='family'),
        ),
    ]
