# Generated by Django 4.2.2 on 2023-06-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_tablemodel_name_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='capacity',
            field=models.CharField(choices=[('one', 1), ('two', 2), ('four', 4), ('six', 6)], default='four'),
        ),
    ]
