# Generated by Django 4.2.2 on 2023-06-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_tablemodel_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='capacity',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two'), (4, 'four'), (6, 'six')], default=4),
        ),
    ]
