# Generated by Django 4.2.2 on 2023-06-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_tablemodel_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='customer',
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='full_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
