# Generated by Django 4.2.2 on 2023-06-21 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0008_remove_reservationmodel_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reserve', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
