# Generated by Django 4.2.2 on 2023-06-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_reservationmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='user',
        ),
    ]
