# Generated by Django 4.2.2 on 2023-07-13 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0010_remove_reservationmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='user',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
