# Generated by Django 4.2.2 on 2023-07-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_reservationmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='full_name',
        ),
    ]
