# Generated by Django 4.2.2 on 2023-07-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_reservationmodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='email',
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='phone',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
