# Generated by Django 4.2.2 on 2023-07-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_alter_tablemodel_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemodel',
            name='code',
            field=models.CharField(default=1, max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablemodel',
            name='name_type',
            field=models.CharField(choices=[('family', 'Family'), ('individual', 'Individual'), ('couples', 'Couples'), ('friends', 'Friends'), ('business', 'Business')], default='family'),
        ),
    ]
