# Generated by Django 4.2.2 on 2023-07-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_tablemodel_code_alter_tablemodel_name_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
