# Generated by Django 4.2.2 on 2023-07-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_alter_tablemodel_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationmodel',
            options={'verbose_name': 'Reservacion', 'verbose_name_plural': 'Reservaciones'},
        ),
        migrations.AlterModelOptions(
            name='tablemodel',
            options={'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
    ]
