# Generated by Django 4.2.2 on 2023-07-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_alter_reservationmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='hour',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
