# Generated by Django 4.2.2 on 2023-08-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_alter_reservationmodel_checkin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationmodel',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='tablemodel',
            options={'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
    ]
