# Generated by Django 4.2.2 on 2023-08-04 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0022_alter_reservationmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemodel',
            name='assigned_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
