# Generated by Django 4.2.2 on 2023-07-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_suppliermodel_customermodel_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(max_length=101),
        ),
    ]
