# Generated by Django 4.2.2 on 2023-06-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordersmodel_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailmodel',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
