# Generated by Django 4.2.2 on 2023-06-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderdetailmodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='total_amount_currency',
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
