# Generated by Django 4.2.2 on 2023-06-29 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_ordersmodel_total_amount_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='table',
        ),
    ]
