# Generated by Django 4.2.2 on 2023-07-11 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderdetailmodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailmodel',
            name='status',
        ),
    ]
