# Generated by Django 4.2.2 on 2023-07-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orderdetailmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Facturado', 'facturado')], default='Pending', max_length=20),
        ),
    ]
