# Generated by Django 4.2.2 on 2023-07-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_ordersmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Invoiced', 'invoiced')], default='Pending', max_length=20),
        ),
    ]
