# Generated by Django 4.2.2 on 2023-07-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderdetailmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailmodel',
            name='comentario',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
