# Generated by Django 4.2.2 on 2023-08-01 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_ordersmodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='customer',
        ),
    ]
