# Generated by Django 4.2.2 on 2023-06-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_suppliermodel_customermodel_created_and_more'),
        ('products', '0004_alter_employeemodel_hiredate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.suppliermodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategorymodel'),
        ),
    ]
