# Generated by Django 4.2.2 on 2023-06-16 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_warehouse_delete_warehousedetailmodel2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warehouse',
            new_name='WarehouseModel',
        ),
        migrations.AddField(
            model_name='warehousedetailmodel',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.warehousemodel'),
            preserve_default=False,
        ),
    ]
