# Generated by Django 4.2.2 on 2023-06-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_warehouse_warehousemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousemodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
