# Generated by Django 4.2.2 on 2023-06-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_warehousemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousemodel',
            name='adress',
            field=models.CharField(max_length=100),
        ),
    ]
