# Generated by Django 4.2.2 on 2023-06-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_warehousemodel_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
