# Generated by Django 4.2.2 on 2023-07-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productmodel_price_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combomodel',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='combomodel',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='combomodel',
            name='stock',
            field=models.FloatField(default=0),
        ),
    ]
