# Generated by Django 4.2.2 on 2023-07-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_combomodel_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combomodel',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='products.productmodel'),
        ),
    ]
