# Generated by Django 4.2.2 on 2023-07-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_combomodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combomodel',
            name='product',
            field=models.ManyToManyField(blank=True, to='products.productmodel'),
        ),
    ]
