# Generated by Django 4.2.2 on 2023-07-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_combomodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combomodel',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='combos', to='products.productmodel'),
        ),
    ]
