# Generated by Django 4.2.2 on 2023-07-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_combomodel_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combomodel',
            options={'verbose_name': 'Combo', 'verbose_name_plural': 'Combos'},
        ),
        migrations.AlterModelOptions(
            name='employeemodel',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='productcategorymodel',
            options={'verbose_name': 'Cat Producto', 'verbose_name_plural': 'Cat Productos'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='warehousedetailmodel',
            options={'verbose_name': 'Cat Almacen', 'verbose_name_plural': 'Cat Almacenes'},
        ),
        migrations.AlterModelOptions(
            name='warehousemodel',
            options={'verbose_name': 'Almacen', 'verbose_name_plural': 'Almacenes'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default=1, upload_to='product'),
            preserve_default=False,
        ),
    ]
